// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCN33gBwHgTC6V3YnO3pDDlBUtB2AOZe8',
    appId: '1:663917254212:web:193ee2974e8d6bfdc1ce11',
    messagingSenderId: '663917254212',
    projectId: 'flowslot-booking-system',
    authDomain: 'flowslot-booking-system.firebaseapp.com',
    storageBucket: 'flowslot-booking-system.firebasestorage.app',
    measurementId: 'G-3YTSY0575Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-7sypzqrrXkLUhi95xGztA8Ud3fDSbo',
    appId: '1:663917254212:android:b7f455ec9667f5a8c1ce11',
    messagingSenderId: '663917254212',
    projectId: 'flowslot-booking-system',
    storageBucket: 'flowslot-booking-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUPXANJBzuJbIkE14Fhz9yuArhLO4oJhg',
    appId: '1:663917254212:ios:4db14e64512b9cc6c1ce11',
    messagingSenderId: '663917254212',
    projectId: 'flowslot-booking-system',
    storageBucket: 'flowslot-booking-system.firebasestorage.app',
    iosBundleId: 'com.example.bookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUPXANJBzuJbIkE14Fhz9yuArhLO4oJhg',
    appId: '1:663917254212:ios:4db14e64512b9cc6c1ce11',
    messagingSenderId: '663917254212',
    projectId: 'flowslot-booking-system',
    storageBucket: 'flowslot-booking-system.firebasestorage.app',
    iosBundleId: 'com.example.bookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCN33gBwHgTC6V3YnO3pDDlBUtB2AOZe8',
    appId: '1:663917254212:web:12551840ffa30dd3c1ce11',
    messagingSenderId: '663917254212',
    projectId: 'flowslot-booking-system',
    authDomain: 'flowslot-booking-system.firebaseapp.com',
    storageBucket: 'flowslot-booking-system.firebasestorage.app',
    measurementId: 'G-68GRGMY95Q',
  );
}
